services:
  - type: web
    name: realtime-meeting-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mansikundwani_db_user:kundwanime03@realtimeappcluster.zhknxqv.mongodb.net/realtimeapp?retryWrites=true&w=majority&appName=RealTimeAppCluster
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
